Added architecture design methodology article in blog section
ECE3SAT/ece3sat.github.io pull request #4
Opened 2018-01-31 17:01 UTC by quelqun007

I pushed an article online, but i'm not sure for the header : should we add *alias* ?

2018-01-31 17:11 UTC, Nodraak commented
The `alias` key of the header should not be used.

2018-02-01 08:53 UTC, Nodraak requested changes

2018-02-01 08:53 UTC, Nodraak commented on content/Blog/2018-02-01-design-the-best-architecture-ever.md
> +- how these documents are laid out (i.e.,modelling techniques, notation, semantics, etc.), and so on.
There should be a space after commas

2018-02-01 08:53 UTC, Nodraak commented on content/Blog/2018-02-01-design-the-best-architecture-ever.md
> +Then we take into account the reviews from each module’s team. Indeed, they had to read and verify the documented architecture produced to ensure it matches the set of their own requirements. If one
No space before colons

2018-02-01 09:57 UTC, AodhAnd requested changes
Here are my comments ! ;) Most of them are suggestions, but some of them definitely need to be taken into account.
Otherwise, it seems good to me

2018-02-01 09:57 UTC, AodhAnd commented on content/Blog/2018-02-01-design-the-best-architecture-ever.md
> +We previously presented our 5 modules ADCS, TCS, OBC, EDT and EPS. Our architecture has to create subsystems in terms of hardware, communication and energy, while respecting spatial requirements and
This is what I would rather say: "the most fault-tolerant possible"

2018-02-01 09:57 UTC, AodhAnd commented on content/Blog/2018-02-01-design-the-best-architecture-ever.md
> +First of all, we had to gather all requirements from each module. The previous phase focused on it and used formalism to describe it in their reports. However, some requirements had to be updated, th
"communication with other modules" ?

2018-02-01 09:57 UTC, AodhAnd commented on content/Blog/2018-02-01-design-the-best-architecture-ever.md
> +We kept in mind that any information has to be saved (even if it’s written on a napkin). Indeed, we have to be able to make our choices understandable by future working teams.
"every information should be somehow logged and saved" ?
"make ~our~ choices that are understandable"

2018-02-01 09:57 UTC, AodhAnd commented on content/Blog/2018-02-01-design-the-best-architecture-ever.md
> +>This is done by decomposing the entire embedded system into hardware and/or software elements, and then further decomposing the elements that need breaking down. These decompositions are represented
It would be nice to have a special style for quotes (currently this just looks like a shifted ordinary paragraph and it's weird...)
@nodraak ?

2018-02-01 09:57 UTC, AodhAnd commented on content/Blog/2018-02-01-design-the-best-architecture-ever.md
> +This step involves creating a table of contents that outlines the information and documentation available for the architecture, such as:
Insert a line between the list item and the description of the item or the Markdown engine considers this as a single paragraph and it looks weird.

2018-02-01 09:57 UTC, AodhAnd commented on content/Blog/2018-02-01-design-the-best-architecture-ever.md
> +This step involves creating a table of contents that outlines the information and documentation available for the architecture, such as:
Also insert an empty line after the column sign (for the same reason: if not, the itemized list isn't shown properly)

2018-02-01 09:57 UTC, AodhAnd commented on content/Blog/2018-02-01-design-the-best-architecture-ever.md
> +>This document should indicate which requirements are being supported by the structure and how these requirements are being supported by the design, as well as any relative constraints, issues, or op
Same thing for the quote environment, this looks weird as of now...

2018-02-01 09:57 UTC, AodhAnd commented on content/Blog/2018-02-01-design-the-best-architecture-ever.md
> +Then we take into account the reviews from each module’s team. Indeed, they had to read and verify the documented architecture produced to ensure it matches the set of their own requirements. If one
"Then we took"

2018-02-01 09:57 UTC, AodhAnd commented on content/Blog/2018-02-01-design-the-best-architecture-ever.md
> +Then we take into account the reviews from each module’s team. Indeed, they had to read and verify the documented architecture produced to ensure it matches the set of their own requirements. If one
"their own set of requirements"

2018-02-01 09:57 UTC, AodhAnd commented on content/Blog/2018-02-01-design-the-best-architecture-ever.md
> +Then we take into account the reviews from each module’s team. Indeed, they had to read and verify the documented architecture produced to ensure it matches the set of their own requirements. If one
"following the same process"

2018-02-01 09:57 UTC, AodhAnd commented on content/Blog/2018-02-01-design-the-best-architecture-ever.md
> +#### summary:
Summary

2018-02-01 09:57 UTC, AodhAnd commented on content/Blog/2018-02-01-design-the-best-architecture-ever.md
> +#### summary:
You can maybe remove the ':' sign.

2018-02-01 09:57 UTC, AodhAnd commented on content/Blog/2018-02-01-design-the-best-architecture-ever.md
> +### SOURCES
No need for all caps here ?..

2018-02-01 09:57 UTC, AodhAnd commented on content/Blog/2018-02-01-design-the-best-architecture-ever.md
> +[Link to ScholarVox](http://scholarvox.campuseiffel.fr/book/40000649)
Hum... Isn't it possible to redirect to another public link instead of a link that is specific to "Campus Eiffel" ?

2018-02-01 09:57 UTC, AodhAnd commented on content/Blog/2018-02-01-design-the-best-architecture-ever.md
> +>}}
Please remove the text on the image that says "FIGURE 11.1 [...]" !!

2018-02-01 10:17 UTC, AodhAnd approved these changes

2018-02-01 10:18 UTC, merged